### ISSUE TITLE
Create new bundle/release with latest configs

### ISSUE THREAD

**Issue by perosb** [OpenZWave/python-openzwave#105]
Hi,

is it possible to create a new tagged release with the latest configs?
Even though it is possible to build using flavor=git, it's more convenient to have a specific version as a dependency.

Maybe this is something that could be automated just bumping the patch version with latest configs? What are your thoughts?

br

**Comment by skeptizzle** [comment]
I'm looking forward to new configs as well.. I have a Fibaro Co2 sensor and a Philio Motion sensor that are currently unsupported by Home-assistant..

**Comment by bibi21000** [comment]
Hi
You can use the embed_shared favor and put your conf in /etc/openzwave. This is the first place where the lib looks for config files : 
https://github.com/OpenZWave/python-openzwave/blob/master/src-lib/libopenzwave/libopenzwave.pyx#L606

**Comment by rogersmj** [comment]
People on hass.io can't use the workaround to obtain new configs, I don't think, because of the way the docker container is setup (?). It's not possible to get to those files. We really need a new patch release that includes the latest configs.

**Comment by rogersmj** [comment]
Hi @bibi21000 , not having more frequent releases of python-openzwave is becoming an increasing problem in the Home Assistant community. Would you consider doing a patch release with the new configs, or can you allow someone else to take a larger role in the project and issue those releases?

**Comment by dshokouhi** [comment]
Hello, I think another release would be great for the home assistant community.  There are so many install flavors that a release from here would be the best way to get it out to everyone.  The community would greatly appreciate all recent fixes as well :)

**Comment by bibi21000** [comment]
@rogersmj : 
What is the problem with the workaround ?

**Comment by DubhAd** [comment]
The issue is that because of the way Hass.io works (Docker containers) people can't just apply the workaround themselves - they don't have access.

**Comment by rogersmj** [comment]
@bibi21000 Yep, exactly what @DubhAd said. Hass.io is becoming the preferred method to install HA because it's so relatively hassle-free and doesn't require you to muck around with server administration -- makes it more like an appliance, which is opening up HA to a lot more people. The downside is that anything that requires hacky workarounds -- modifying source/library files -- can't really be done on Hass.io. So we really need a new release of python-openzwave to incorporate all the latest device configs from openzwave's master branch to truly solve this.

**Comment by bibi21000** [comment]
Almost everything can be done with docker ;) I use to test python-openzwave installation :)
Which flavor is used for Hass.io ? Or does it use the make way to install python-openzwave ?
Do you have a link to the Dockerfile ?
Maybe devs can use git ou git_shared flavors: it  will download the last openzwave release and build it for python-openzwave (https://github.com/OpenZWave/python-openzwave/blob/master/Makefile#L769)
It's also possible to use the shared flavor, but in this case devs must download openzwave and build it in the docker build process.
It's also possible to use docker's volume to let users updating configuration files
By the way, if you don't have access (by ssh or other method) to copy configuration files, I can't see how you can update the python-openzwave egg !

**Comment by bibi21000** [comment]
For the shared flavor, look at https://github.com/OpenZWave/docker-openzwave/blob/master/Dockerfile

**Comment by perosb** [comment]
I assume Hass downloads the package as a runtime dependency IF the user has enabled zwave. If the official package doesn't look for "shared" config files at all a custom package must be built like you say. That would be installed for all users then regardless if they want zwave or not.

Maybe it's possible to make "shared" default? If they exist in /etc otherwise fallback to bundled.

**Comment by rogersmj** [comment]
I don't know the intricacies of how Hass.io is setup. However before I came here and filed an issue I asked, explicitly, if such files as python-openzwave could be accessed/edited from the access level Hass.io provides via the SSH add-on, and was told unequivocally that they cannot. Which philosophically makes sense because such access would defeat the purpose of Hass.io, which is to hide all the dependency management and system administration and make it as bulletproof as possible.

**Comment by bibi21000** [comment]
@perosb : if it's impossible to add a simple --install-option="--flavor=git" to the install process of python-openzwave, I can't see how it should be possible to download/config/build openzwave before using the shared flavor
@rogersmj : you can also access of a docker image using bash
Can you provide a link on how the zwave package is download/build/installed ?

**Comment by perosb** [comment]
I'll check with hass devs. Though they are only installed when the package is installed right?

I'm no expert in this but when I tried that, the install option is passed to the dependencies too, and they throw something like "unknown parameter: install option". Once the dependencies are installed, it can be passed only to python-openzwave though.

**Comment by todschmidt** [comment]
Hass and HassIO will not use github dependencies It will only work with pypi released libraries.

**Comment by SebasT87** [comment]
^^ Another HASS user looking for a solution

**Comment by bibi21000** [comment]
@perosb : 
Though they are only installed when the package is installed right? 
I don't understand. Sorry, english is not my native language
Yes you must install dependencies before using flavors : look a readme.rst

**Comment by dshokouhi** [comment]
@bibi21000 is there any reason why we can't get another release?  Workarounds will not be sufficient enough for all users in home assistant, we appreciate the recommendation but it won't work for everyone.   The last release from your team was more than 6 months ago but before that releases were happening all the time, even 2 in a day!  All we are asking is for another release.  6 months is a long time.

**Comment by simonk83** [comment]
I'm in the same boat, but in my case I've just submitted a pull request to add a new device, so my worry is that a new release will be made now, then my pull will be eventually merged, then it'll be another 6 months before another release ;)

Is there any way we can get much more regular releases again (I know this is being discussed above).  It'd be good to get a Hass developer in here as well to talk through the options if possible.  Building openzwave on demand seems like a great solution, but as above I've no idea how possible that is with Hass.

I'd be happy enough to just get at the config files for openzwave in the Hass dockerfile and add the new devices myself, but so far I haven't been able to work out how to do that.  As bibi said it may just be a case of SSH'ing as root and then bashing into the docker.  I'll have to try that tonight when I have access to my box, I'll post back if I get it working.

**Comment by rogersmj** [comment]
^ Yeah but even if you can do that, wouldn't that potentially compromise how Hass.io is designed to work? Potentially every time you update it, such changes might get overwritten. And more and more people are going to be running into this problem as more time goes by, and most of them aren't going to be up to doing that sort of workaround. The whole reason the Hass.io variant of HA exists -- and is getting so popular -- is because it's for people who want to run Home Assistant WITHOUT doing hacky workarounds or server administration work. So...again...we really need a new package release of python-openzwave that includes new device configs. And if the current maintainers aren't going to bother doing it, they need to invite someone else in to help or it needs to get forked. HA/Hass.io can't be dependent on such a critical library that isn't being actively maintained.

**Comment by bibi21000** [comment]
@dshokouhi : 
simply because there is no update :D python-openzwave is simply a wrapper to the c++ library, not a lopenzwave library implemented in python. And if you look closer to commits, you surely find that I create more than 5 bundles a day : that is called development !!!

@rogesmj : 
thanks for your comments but it should be in the hass.io issues. The way homeassistant use python-openzwave is not the right one, please report it to home assistant devs. In the past, python-openzwave use makefile to compile, and home-assistant devs use it. So it seems that they update to use pip ... but in the wrong way. If they can't add a simple option to the installation process maybe they can revert to the old method (using makefile) !!!
What you really need is new configs (and openzwave code) in homeassistant, NOT A NEW RELEASE of python-openzwave : and it's available in the current version !!!

@simonk83 : 
as said here and in the readme, there is many ways to get fresh config files : for users and for developpers. But don't know why, devs seems don't want to use them (that is what most people here says) !!!
If you can provide a link on the way the hass.io is done (seems to be a Dockerfile), surely I can help you !!! 
I ask it for days but nobody give it !!!

**Comment by perosb** [comment]
@bibi21000 I open a tracking issue with hass and maybe we can get some developers input. https://github.com/home-assistant/home-assistant/issues/11895

Since this is runtime dependencies based on the end users configuration I don't think this is in any Dockers. Surely it can be done.
https://github.com/home-assistant/hassio/blob/dev/Dockerfile

**Comment by rofrantz** [comment]
@all do u think it would be a good idea have the configs in a separate repo ?

**Comment by Fishwaldo** [comment]
@All - the Dev branch of OZW has the ability to automatically download updated config files. 
So my advice is anything you do right now should be a stop gap measure. 

I can’t say how long till we merge Dev into master (and the language wrappers update) right now though. Just a FYI.

**Comment by todschmidt** [comment]
@bibi21000 First off thanks for your work on this, you definitely stay busy. Hassio and homeassistant both use pip to install packages. Hassio uses docker containers, but does not materially affect how the install is done.

I get that the code itself hasn't changed but the git has configs that do need updating. HA has made a decision to not create dependencies on git repositories and only use packages that are released and available via pip for what seems to me a pretty valid reason. Using pip to install from git isn't the right way to do it since it would still leave users with different versions of the config depending on when they installed or updated HA. This would be unsupportable because it gives no way for us to ensure version X has X configs. We also have no way to update down the road since the version number doesn't change, so we would need to do something hacky like rerun the pip install every time for just this package. Even having the ability to use configs from /etc/openzwave like in the dev version is a lot less clean since we would need to do something to ensure those were updated and also breaks some of the philosophy of using virtualenvs to segregate things.

Could you explain more your opposition to releasing a new package?

**Comment by DubhAd** [comment]
@Fishwaldo That's awesome news for the future, and I'm sure it's going to make everybody's life easier. Thanks.

**Comment by bibi21000** [comment]
@tschmidty69 : 

Are you a hass.io developper ?

> I get that the code itself hasn't changed but the git has configs that do need updating. HA has made a decision to not create dependencies on git repositories and only use packages that are released and available via pip for what seems to me a pretty valid reason. 

That is the choice of developpers and that may be a good way to use mature projects. But last release of openzwave (config files) was in Aug 2016. Config files in openzwave are updated many times a day. 

> Using pip to install from git isn't the right way to do it since it would still leave users with different versions of the config depending on when they installed or updated HA.This would be unsupportable because it gives no way for us to ensure version X has X configs.

Using pyozw_check, you can get the day and the time of build

> We also have no way to update down the road since the version number doesn't change, so we would need to do something hacky like rerun the pip install every time for just this package. Even having the ability to use configs from /etc/openzwave like in the dev version is a lot less clean since we would need to do something to ensure those were updated and also breaks some of the philosophy of using virtualenvs to segregate things.

If you look for a more virtualenv friendly path to store your config files, look at venv2/lib/python2.7/site-packages/python_openzwave/ozw_config/ . This is the default place where python store them.
Well you will have problem with openzwave in the future in this case (when the dev branch will become stable).

> Could you explain more your opposition to releasing a new package?

- The embeded package is simply a hack to get new unreleased openzwave code and configs. Looking at what @Fishwaldo  said, I think it will be removed in the future.

- A good case study : @simonk83  submit a PR for openzwave yesterday and he want a new release. Today he revert its changes and submit new one. What do you want : a daily package of python-openzwave. It will surely be less support for you but surely more for me. The solution used to this case study is to use the git flavor.

- Creating a new bundle creates 2 zip of approximatively 2 Mb which are stored in git. That's really annoying for developpers/people that clone this repository from github.

- I don't have the time to make a new bundle everytime a hass.io user buy a new device. Testing and releasing a new bundle takes approximativelly 2 hours (for python tests and some devices tests)

- There are many ways of doing what you want actually. Maybe can I add the usage of prebuilt packages (http://www.openzwave.com/downloads/stable-releases) with the flavor --shared

- There are already hacks in home-assistant ie telldus

**Comment by todschmidt** [comment]
Thanks for your response. No one would expect you to update daily or even weekly, but once every month or two would be really helpful.

I just ran the install like this 

```
pip3 install python-openzwave --upgrade --force-reinstall --install-option="--flavor=git" --no-deps
```

It took about 3 1/2 minutes to rebuild on my hass box. Is there a better way you would recommend  updating the configs?

**Comment by bibi21000** [comment]
I've never said that before in 15 years of free software development but please RTFM.
I've add a new way to update config files in the new release : please asks HASS developpers to use it !!! (https://github.com/OpenZWave/python-openzwave/blob/master/src-api/openzwave/controller.py#L1354)

**Comment by perosb** [comment]
@bibi21000 Thanks a lot for doing this! I'll close this issue as the update is complete.

**Comment by todschmidt** [comment]
@bibi21000 Thanks, I'll take a look at implementing that function.

**Comment by SebasT87** [comment]
@bibi2100 thanks!
