### ISSUE TITLE
Why useing obsolet "_thread" as thread on network.py

### ISSUE THREAD

**Issue by ThomasCr** [OpenZWave/python-openzwave#110]
Hi,

is there any important reason to use the obsolet  _thread (function based) and not the threading (class based) Implementation for python3 ?

Because its not so nice to mix both together in my project. I get AssertionError exceptions with it.

**Comment by bibi21000** [comment]
Hi,
The _thread import will be removed in the next version.
Where have you seen that the _thread module is obsolet ?
From the official documentation : https://docs.python.org/3/library/threading.html

> This module constructs higher-level threading interfaces on top of the lower level _thread module.

**Comment by ThomasCr** [comment]
sorry, I found the information on https://www.python-course.eu/threads.php

> Please note: The thread module has been considered as "deprecated" for quite a long time. Users have been encouraged to use the threading module instead. So,in Python 3 the module "thread" is not available anymore. But that's not really true: It has been renamed to "_thread" for backwards incompatibilities in Python3.

**Comment by linehammer** [comment]
It's been quite a long time since the low-level [thread](http://net-informations.com/python/pro/threading.htm) module was informally deprecated, with all users heartily encouraged to use the higher-level threading module instead; now with the ability to introduce backwards incompatibilities in Python 3.
