### ISSUE TITLE
Why is the installation so non-standard?

### ISSUE THREAD

**Issue by piec** [OpenZWave/python-openzwave#51]
Hi,

Thanks for making this python binding.
I'm using linux and the git version of python-openzwave, I was wondering why the installation of this package is so non-standard? why can't we just `pip install python-openzwave`?
Also why does `make build` clone its own version of openzwave and build it although I already have it installed (.so, .h, ozw_config, .pc, ...)

Cheers

**Comment by bibi21000** [comment]
If someone is interessed in, here is a response sent to about the pip stuff

Thanks for all but :
- i known how version works and github too. If python-openzwave is in beta version that's because it's simply not stable. As you surely seen all the tag stuff is in the makefile.
- as you said, why whange something that works : the makefile ?? There is probably some missing dependencies but which one ?
- the doc is here because it it automatically pusblished on other site which doesn't have the dependencies
- the included openzwave is used by the archive install type which is the only one works on some ubuntu 64. It also remove the cython dependency which is a must one on a raspberry.
- the setup.py is able to use linked release of the libopenzwave library (for the debian packages)
- I think api should be refactor, specially the part of the node implementation.
- Don't know which devices you have but you can make tests for them too
- for Pipy, I'm ok for an installation process like zmq : using the the installed libopenzwave (with cython) or install the embeded one (without cython)
  I think there is a lot of things to be done before changing the makefile ... The most problem with the makefile are user which doesn't read the docs ;)
  So do what you wan't but if it breaks some important things I will not accept the PR. But if it's a real improvement I'm ok
  All the best

**Comment by bibi21000** [comment]
Duplicate #59
