### ISSUE TITLE
Why patch ValueID.h?

### ISSUE THREAD

**Issue by Cadair** [OpenZWave/python-openzwave#54]
Hello,

I am trying to build python-openzwave against the arch linux system openzwave library, so that I can easily build other things against the same openzwave library, and because I assume it is the preferred way of building arch packages.

However, building python-openzwave with the `--debian-package` flag to `setup-lib.py` fails unless I patch the openzwave system library with this patch: https://github.com/OpenZWave/python-openzwave/blob/master/Makefile#L272

Could you explain to me what this does because it's way over my head.

Thanks

**Comment by bibi21000** [comment]
Hi

> I am trying to build python-openzwave against the arch linux system openzwave library, so that I can easily build other things against the same openzwave library, and because I assume it is the preferred way of building arch packages.

yes it is. Same for ubuntu/debian. Look at the debian directory and specialy to the rules file, that's how the debian package is built.

But
At early stage of development, everything works fine with cython 0.14 ... but fails when cython 0.15 arrives : something about valueid must be public.
cython's team doesn't want to reverse the modification (because if it's private it should be exposed).
openzawave doesn't make it public so that's why there is a patch.
Maybe it should be possibile to put it 'public' now in openzwave.
Could you post the full log message.

**Comment by bibi21000** [comment]
Not needed anymore for 0.4
Thanks
