### ISSUE TITLE
Unable to link on Windows

### ISSUE THREAD

**Issue by automaton82** [OpenZWave/python-openzwave#72]
Following the adjusted build process for Windows, everything is working except:

`python setup-lib.py install`

When run, this command fails with:

> fatal error C1905: Front end and back end not compatible (must target same proce
> ssor).
> LINK : fatal error LNK1257: code generation failed

I think because it's trying to use x86 libraries from the windows SDK, but the rest is built in amd64. Any ideas on this?

**Comment by bibi21000** [comment]
Hi, I've updated the process for windows installation
Could you test : https://github.com/OpenZWave/python-openzwave/blob/master/docs/INSTALL_WIN.rst

**Comment by dude0001** [comment]
@automaton82 did you ever get this to work. I am hitting other link issues on the same step.

**Comment by automaton82** [comment]
@dude0001 nope, I gave up and bought SmartThings. Been working flawlessly for over a year with many custom device handlers.

**Comment by dude0001** [comment]
@bibi21000 I don't think this issue needs worknow that [PR # 150](https://github.com/OpenZWave/python-openzwave/pull/150) has been merged.

**Comment by kdschlosser** [comment]
I am going to close this issue. the Windows builds are now working.

@dude0001 if you are not to busy and if you can have a look at PR #182 t some point. In order to get the requirements put into the setup program properly there were some changes made that caused me a bunch of issues with the wheels. I ended up having to create a bdist_wheel class that creates the wheel without using the wheel library. I want to make sure that I didn't miss anything when generating the whl files.
